uint64 timestamp        # time since system start (microseconds)

float32 actuator_1             # Actuator 1
float32 actuator_1_target      # Actuator 1 target
float32 actuator_1_current     # Actuator 1 current 
float32 actuator_1_velocity    # Actuator 1 velocity
float32 actuator_2             # Actuator 2
float32 actuator_2_target      # Actuator 2 target
float32 actuator_2_current     # Actuator 2 current
float32 actuator_2_velocity    # Actuator 2 velocity