#!/bin/sh
#
# @name LEAPFROG Lunar Lander
#
# @type Gimbaled Engine
# @class Copter
#
# @output MAIN1 linear actuator 1
# @output MAIN2 linear actuator 2
# @output MAIN3 null
# @output MAIN4 null
# @output MAIN5 feed-through of RC AUX1 channel
# @output MAIN6 feed-through of RC AUX2 channel
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
# @output AUX4 feed-through of RC FLAPS channel
#
#
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set NAV_ACC_RAD 2

	param set RTL_RETURN_ALT 30
	param set RTL_DESCEND_ALT 10
	param set RTL_LAND_DELAY 0

	param set PWM_MAX 1950
	param set PWM_MIN 1075
	param set PWM_RATE 400

	param set GPS_UBX_DYNMODEL 6
fi

set MAV_TYPE 2

set MIXER lander

set PWM_OUT 123
